// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQR8Fav7voLZdru97HC-JU0mdDZdzTYys',
    appId: '1:325091410901:web:3047ffe3bd6f095ccd735c',
    messagingSenderId: '325091410901',
    projectId: 'flutter-task-manager-a812e',
    authDomain: 'flutter-task-manager-a812e.firebaseapp.com',
    storageBucket: 'flutter-task-manager-a812e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkkv7IiPtg5hwYBHPESlmzLvZ0T2sqR30',
    appId: '1:325091410901:android:c7755213016cff71cd735c',
    messagingSenderId: '325091410901',
    projectId: 'flutter-task-manager-a812e',
    storageBucket: 'flutter-task-manager-a812e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvFYjX-Jxt8bb0xmWa1UAVEx4FIZ_v8j0',
    appId: '1:325091410901:ios:e214b6cc9b0241b5cd735c',
    messagingSenderId: '325091410901',
    projectId: 'flutter-task-manager-a812e',
    storageBucket: 'flutter-task-manager-a812e.firebasestorage.app',
    iosBundleId: 'com.example.flutterTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvFYjX-Jxt8bb0xmWa1UAVEx4FIZ_v8j0',
    appId: '1:325091410901:ios:e214b6cc9b0241b5cd735c',
    messagingSenderId: '325091410901',
    projectId: 'flutter-task-manager-a812e',
    storageBucket: 'flutter-task-manager-a812e.firebasestorage.app',
    iosBundleId: 'com.example.flutterTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQR8Fav7voLZdru97HC-JU0mdDZdzTYys',
    appId: '1:325091410901:web:5a17d2bbe5e5368fcd735c',
    messagingSenderId: '325091410901',
    projectId: 'flutter-task-manager-a812e',
    authDomain: 'flutter-task-manager-a812e.firebaseapp.com',
    storageBucket: 'flutter-task-manager-a812e.firebasestorage.app',
  );

}